In [1]:
import pandas as pd

In [2]:
import os

filepaths = [os.path.join("C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\", f"BJ_1\\IoTpond{i}.csv") for i in range(1, 13) if i != 5]
filepaths

['C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\BJ_1\\IoTpond1.csv',
 'C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\BJ_1\\IoTpond2.csv',
 'C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\BJ_1\\IoTpond3.csv',
 'C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\BJ_1\\IoTpond4.csv',
 'C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\BJ_1\\IoTpond6.csv',
 'C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\BJ_1\\IoTpond7.csv',
 'C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\BJ_1\\IoTpond8.csv',
 'C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\BJ_1\\IoTpond9.csv',
 'C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\BJ_1\\IoTpond10.csv',
 'C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\BJ_1\\IoTpond11.csv',
 'C:\\Users\\DELL\\Documents\\Amrita\\Solutions\\firebase_gdsc\\BJ_1\\IoTpond12.csv']

In [3]:
df1=pd.read_csv(filepaths[0])
print(df1.shape)
print(df1.isnull().sum())
df1.dropna(axis=0, inplace=True)
print(df1.isnull().sum())
print(df1.shape)
df1

(83126, 11)
created_at                 0
entry_id                   0
Temperature (C)            0
Turbidity(NTU)             0
Dissolved Oxygen(g/ml)     0
PH                         0
Ammonia(g/ml)             52
Nitrate(g/ml)              0
Population                 0
Fish_Length(cm)            2
Fish_Weight(g)             2
dtype: int64
created_at                0
entry_id                  0
Temperature (C)           0
Turbidity(NTU)            0
Dissolved Oxygen(g/ml)    0
PH                        0
Ammonia(g/ml)             0
Nitrate(g/ml)             0
Population                0
Fish_Length(cm)           0
Fish_Weight(g)            0
dtype: int64
(83072, 11)

,created_at,entry_id,Temperature (C),Turbidity(NTU),Dissolved Oxygen(g/ml),PH,Ammonia(g/ml),Nitrate(g/ml),Population,Fish_Length(cm),Fish_Weight(g)
0,2021-06-19 00:00:05 CET,1889,24.8750,100,4.505,8.43365,0.45842,193,50,7.11,2.91
1,2021-06-19 00:01:02 CET,1890,24.9375,100,6.601,8.43818,0.45842,194,50,7.11,2.91
2,2021-06-19 00:01:22 CET,1891,24.8750,100,15.797,8.42457,0.45842,192,50,7.11,2.91
3,2021-06-19 00:01:44 CET,1892,24.9375,100,5.046,8.43365,0.45842,193,50,7.11,2.91
4,2021-06-19 00:02:07 CET,1893,24.9375,100,38.407,8.40641,0.45842,192,50,7.11,2.91
...,...,...,...,...,...,...,...,...,...,...,...
83121,2021-10-13 02:48:31 CET,247201,26.5625,100,0.441,2.56412,5.91282,946,50,33.45,318.64
83122,2021-10-13 03:17:36 CET,247273,26.5625,100,1.020,2.67760,4.21414,985,50,33.45,318.64
83123,2021-10-13 03:46:49 CET,247336,26.5000,100,0.852,2.45063,8.18873,963,50,33.45,318.64
83124,2021-10-13 04:13:23 CET,247402,26.3750,100,4.850,2.41885,10.62411,944,50,33.45,318.64
83125,2021-10-13 04:14:22 CET,247405,26.3750,100,1.279,2.40524,10.07556,943,50,33.45,318.64

In [4]:
# prompt: in the csv file there are too many rows, decrease it without losing much data

# Reduce the number of rows by taking every nth row
n = 50
df1 = df1.iloc[::n]

# Print the new shape and data
print(df1.shape)
print(df1)

(1662, 11)
                    created_at  entry_id  Temperature (C)  Turbidity(NTU)  \
0      2021-06-19 00:00:05 CET      1889          24.8750             100
50     2021-06-19 00:22:56 CET      1951          24.8750             100
100    2021-06-19 00:44:48 CET      2015          24.8125             100
150    2021-06-19 01:08:37 CET      2084          24.7500             100
200    2021-06-19 01:30:23 CET      2149          24.6875             100
...                        ...       ...              ...             ...
82904  2021-09-30 06:42:38 CET    217295          24.8125             100
82954  2021-10-11 22:51:05 CET    243403          27.1875             100
83004  2021-10-12 06:57:26 CET    244444          26.3750             100
83054  2021-10-12 14:34:25 CET    245563          26.8750             100
83104  2021-10-12 23:39:12 CET    246767          26.8125             100

       Dissolved Oxygen(g/ml)       PH  Ammonia(g/ml)  Nitrate(g/ml)  \
0                       4.505  8.43365        0.45842            193
50                      6.694  8.42911        0.45842            189
100                     4.488  8.44272        0.45842            187
150                    12.593  8.42911        0.45842            199
200                     9.212  8.42457        0.45842            195
...                       ...      ...            ...            ...
82904                   0.388 -0.30482       34.96413           1183
82954                   4.660  3.90780        8.79546           1040
83004                   0.632  4.29365        6.39497            946
83054                   2.710  4.18471        3.70036           1018
83104                   0.616  2.54596        3.20135           1197

       Population  Fish_Length(cm)  Fish_Weight(g)
0              50             7.11            2.91
50             50             7.11            2.91
100            50             7.11            2.91
150            50             7.11            2.91
200            50             7.11            2.91
...           ...              ...             ...
82904          50            32.05          280.15
82954          50            33.31          313.72
83004          50            33.38          316.18
83054          50            33.38          316.18
83104          50            33.38          316.18

[1662 rows x 11 columns]

In [26]:
# Python
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.multioutput import MultiOutputRegressor

# Assuming df1 is your DataFrame
X = df1.drop(['Fish_Weight(g)','Fish_Length(cm)','created_at'], axis=1)  
y = df1[['Fish_Weight(g)','Fish_Length(cm)']]  # We will predict 'Fish_Weight(g)' and 'Fish_Length(cm)'

# Convert categorical data to numerical if any
X = pd.get_dummies(X)

# Split the data into training/testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a multioutput regression object
multioutput_regressor = MultiOutputRegressor(LinearRegression())

# Train the model using the training sets
multioutput_regressor.fit(X_train, y_train)

# Make predictions using the testing set
y_pred = multioutput_regressor.predict(X_test)

# The mean squared error for each target
mse_fish_weight = mean_squared_error(y_test['Fish_Weight(g)'], y_pred[:, 0])
mse_fish_length = mean_squared_error(y_test['Fish_Length(cm)'], y_pred[:, 1])

print('Mean squared error for Fish_Weight(g): %.2f' % mse_fish_weight)
print('Mean squared error for Fish_Length(cm): %.2f' % mse_fish_length)

Mean squared error for Fish_Weight(g): 188.88
Mean squared error for Fish_Length(cm): 1.44

In [1]:
length = # input length
weight = # input weight

if length >= 20 and length <= 26 and weight >= 15 and weight <= 25:
    fish_type = "Rui"
elif length >= 15 and length <= 25 and weight >= 18 and weight <= 30:
    fish_type = "Koi"
elif length >= 18 and length <= 30 and weight >= 20 and weight <= 25:
    fish_type = "Silvercarp"
elif length >= 20 and length <= 25 and weight >= 20 and weight <= 25:
    fish_type = "Karpio"
else:
    fish_type = "Unknown"

print("Fish Type:", fish_type)
print("Length:", length)
print("Weight:", weight)

SyntaxError: invalid syntax (3235508665.py, line 1)

In [8]:
# Calculate training accuracy and MSE for SVR
train_accuracy_svr = multioutput_regressor_svr.score(X_train, y_train)
test_accuracy_svr = multioutput_regressor_svr.score(X_test, y_test)
mse_train_svr = mean_squared_error(y_train, multioutput_regressor_svr.predict(X_train))
mse_test_svr = mean_squared_error(y_test, y_pred_svr)

# Calculate training accuracy and MSE for Decision Tree
train_accuracy_dt = multioutput_regressor_dt.score(X_train, y_train)
test_accuracy_dt = multioutput_regressor_dt.score(X_test, y_test)
mse_train_dt = mean_squared_error(y_train, multioutput_regressor_dt.predict(X_train))
mse_test_dt = mean_squared_error(y_test, y_pred_dt)

print('SVR - Training Accuracy: %.2f' % train_accuracy_svr)
print('SVR - Testing Accuracy: %.2f' % test_accuracy_svr)
print('SVR - Training MSE: %.2f' % mse_train_svr)
print('SVR - Testing MSE: %.2f' % mse_test_svr)

print('Decision Tree - Training Accuracy: %.2f' % train_accuracy_dt)
print('Decision Tree - Testing Accuracy: %.2f' % test_accuracy_dt)
print('Decision Tree - Training MSE: %.2f' % mse_train_dt)
print('Decision Tree - Testing MSE: %.2f' % mse_test_dt)

SVR - Training Accuracy: -0.12
SVR - Testing Accuracy: -0.13
SVR - Training MSE: 613.83
SVR - Testing MSE: 758.86
Decision Tree - Training Accuracy: 1.00
Decision Tree - Testing Accuracy: 0.98
Decision Tree - Training MSE: 0.00
Decision Tree - Testing MSE: 19.40

In [30]:
# Assuming df1 is your DataFrame and you want to display the 3rd row
row = df1.iloc[421]  # Remember that Python uses 0-based indexing
print(row)
# Assuming multioutput_regressor is your trained multioutput regression model
input_row = row.drop(['Fish_Weight(g)','Fish_Length(cm)','created_at']).values.reshape(1, -1)
predicted_output = multioutput_regressor.predict(input_row)
predicted_output

created_at                2021-07-01 03:28:39 CET
entry_id                                    25182
Temperature (C)                           24.8125
Turbidity(NTU)                                100
Dissolved Oxygen(g/ml)                       2.04
PH                                        7.84805
Ammonia(g/ml)                          239999.625
Nitrate(g/ml)                                 151
Population                                     50
Fish_Length(cm)                             11.79
Fish_Weight(g)                              14.19
Name: 21061, dtype: object

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[17.33731393, 11.16054503]])

In [12]:
output_row

       Fish_Weight(g)  Fish_Length(cm)
28340           24.82            14.39

In [31]:
import pickle

# Assuming the variable `multioutput_regressor` contains the trained model
with open('ml_model.pkl', 'wb') as file:
    pickle.dump(multioutput_regressor, file)

In [6]:
# Python
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.multioutput import MultiOutputRegressor

# Assuming df1 is your DataFrame
X = df1.drop(['Fish_Weight(g)','Fish_Length(cm)'], axis=1)  
y = df1[['Fish_Weight(g)','Fish_Length(cm)']]  # We will predict 'Fish_Weight(g)' and 'Fish_Length(cm)'

# Convert categorical data to numerical if any
X = pd.get_dummies(X)

# Split the data into training/testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a multioutput regression object with SVR
multioutput_regressor_svr = MultiOutputRegressor(SVR())

# Train the model using the training sets
multioutput_regressor_svr.fit(X_train, y_train)

# Make predictions using the testing set
y_pred_svr = multioutput_regressor_svr.predict(X_test)

# The mean squared error for each target
mse_fish_weight_svr = mean_squared_error(y_test['Fish_Weight(g)'], y_pred_svr[:, 0])
mse_fish_length_svr = mean_squared_error(y_test['Fish_Length(cm)'], y_pred_svr[:, 1])

print('SVR - Mean squared error for Fish_Weight(g): %.2f' % mse_fish_weight_svr)
print('SVR - Mean squared error for Fish_Length(cm): %.2f' % mse_fish_length_svr)

# Create a multioutput regression object with Decision Tree
multioutput_regressor_dt = MultiOutputRegressor(DecisionTreeRegressor())

# Train the model using the training sets
multioutput_regressor_dt.fit(X_train, y_train)

# Make predictions using the testing set
y_pred_dt = multioutput_regressor_dt.predict(X_test)

# The mean squared error for each target
mse_fish_weight_dt = mean_squared_error(y_test['Fish_Weight(g)'], y_pred_dt[:, 0])
mse_fish_length_dt = mean_squared_error(y_test['Fish_Length(cm)'], y_pred_dt[:, 1])

print('Decision Tree - Mean squared error for Fish_Weight(g): %.2f' % mse_fish_weight_dt)
print('Decision Tree - Mean squared error for Fish_Length(cm): %.2f' % mse_fish_length_dt)

SVR - Mean squared error for Fish_Weight(g): 1485.13
SVR - Mean squared error for Fish_Length(cm): 32.59
Decision Tree - Mean squared error for Fish_Weight(g): 38.21
Decision Tree - Mean squared error for Fish_Length(cm): 0.59